### ISSUE TITLE
Cannot find module '@date-fns/upgrade/v2'

### ISSUE THREAD

**Issue by danieldunderfelt** [date-fns/date-fns-upgrade-codemod#5]
I ran the codemod with npx according to the README but I go this error and no files have been modified. I also installed the package in question but it did not help. Am I doing something wrong? I use Yarn btw.

**Comment by danieldunderfelt** [comment]
I got this to work with Yarn by installing it explicitly and then running the command with Yarn. I also needed to install the upgrade package as mentioned as well as a package called "transform-imports". Then I found out that the codemod does not work on files that use decorators.

**Comment by dkozickis** [comment]
Hi @danieldunderfelt! Thank you for reporting this one.

It's not clearly stated in README, but `@date-fns/upgrade/v2` has to be installed as dependency for your project, the one that you're updating. 

1. Install `@date-fns/upgrade/v2` as dependency for your project
2. Run codemod

The codemod should not be a dependency in your project.

Regarding not working on files with decorators - that's something I have missed.

**Comment by msolovyov** [comment]
I use npm, installed @date-fns/upgrade --save and transform-imports --save but still get the same cannot find module when running the npx codemod

`Error: Cannot find module '@date-fns/upgrade/v2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/michael/.npm/_npx/4223/lib/node_modules/@date-fns/upgrade-codemod/src/transform.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/home/michael/.npm/_npx/4223/lib/node_modules/@date-fns/upgrade-codemod/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .ts] (/home/michael/.npm/_npx/4223/lib/node_modules/@date-fns/upgrade-codemod/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
`

**Comment by msolovyov** [comment]
I got it to work by installing this repo locally and running the bin directly
`cd node_modules/@date-fns/upgrade-codemod/bin`
`./date-fns-codemod.js projectdir`

**Comment by dkozickis** [comment]
After further reconsideration @danieldunderfelt is actually correct :) 
I'll merge his PR and publish new lib.

**Comment by dkozickis** [comment]
Closed via #6
